package com.loconoco.tutorials.learningkie;

rule "Greet informal at any time"
when
    not (UseFormalLanguage())

    IsManyPeople()
then
    System.out.println("Wazap dudes");
end

rule "Greet informal at any time"
when
    not (UseFormalLanguage())

    not (IsManyPeople())
then
    System.out.println("Hey bro");
end

rule "Greet formal in the morning"
when
    UseFormalLanguage()

    CurrentHour(hour <= 12)
then
    System.out.println("Good morning");
end

rule "Greet formal in the afternoon"
when
    UseFormalLanguage()

    CurrentHour(hour > 12, hour <= 19)
then
    System.out.println("Good afternoon");
end

rule "Greet formal in the evening"
when
    UseFormalLanguage()

    CurrentHour(hour > 19)
then
    System.out.println("Good evening");
end
